import Img from "../constants/Images";

const popularList = [
  {
    id: 1,
    name: "Mystery",
    bgImg: Img.pupuBg1,
    des: "Mystery fiction can be detective stories in which the emphasis is on the puzzle or suspense element and its logical solution such as a whodunit. ",
  },
  {
    id: 2,
    name: "Picture bookery",
    bgImg: Img.pupuBg2,
    des: "Picture bookery can be detective stories in which the emphasis is on the puzzle or suspense element and its logical solution such as a whodunit. ",
  },
  {
    id: 3,
    name: "Action and adventure",
    bgImg: Img.pupuBg3,
    des: "Action and adventure can be detective stories in which the emphasis is on the puzzle or suspense element and its logical solution such as a whodunit. ",
  },
  {
    id: 4,
    name: "Short story",
    bgImg: Img.pupuBg4,
    des: "Short story can be detective stories in which the emphasis is on the puzzle or suspense element and its logical solution such as a whodunit. ",
  },
  {
    id: 5,
    name: "Comic book",
    bgImg: Img.pupuBg5,
    des: "Comic book can be detective stories in which the emphasis is on the puzzle or suspense element and its logical solution such as a whodunit. ",
  },
  {
    id: 6,
    name: "Science fiction",
    bgImg: Img.pupuBg6,
    des: "Science fiction can be detective stories in which the emphasis is on the puzzle or suspense element and its logical solution such as a whodunit. ",
  },
];

const authorList = [
  {
    id: 1,
    firstName: "Liam",
    lastName: "Noah",
    address: "Cape Town, South Africa",
    following: "2,1k",
    followers: "968k",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author1,
  },
  {
    id: 2,
    firstName: "Noah",
    lastName: "Oliver",
    address: "Cape Town, South Africa",
    following: "1,5k",
    followers: "758k",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author2,
  },
  {
    id: 3,
    firstName: "Oliver",
    lastName: "Elijah",
    address: "Cape Town, South Africa",
    following: "3,2k",
    followers: "1,2m",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author3,
  },
  {
    id: 4,
    firstName: "Elijah",
    lastName: "James",
    address: "Cape Town, South Africa",
    following: "4,1k",
    followers: "845k",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author4,
  },
  {
    id: 5,
    firstName: "Liam",
    lastName: "Noah",
    address: "Cape Town, South Africa",
    following: "6,1k",
    followers: "2,7m",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author3,
  },
  {
    id: 6,
    firstName: "Noah",
    lastName: "Oliver",
    address: "Cape Town, South Africa",
    following: "1,5k",
    followers: "5,2m",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author2,
  },
  {
    id: 7,
    firstName: "Oliver",
    lastName: "Elijah",
    address: "Cape Town, South Africa",
    following: "3,4k",
    followers: "2,2m",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author1,
  },
  {
    id: 8,
    firstName: "Elijah",
    lastName: "James",
    address: "Cape Town, South Africa",
    following: "2,4k",
    followers: "938k",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author4,
  },
  {
    id: 9,
    firstName: "Oliver",
    lastName: "Elijah",
    address: "Cape Town, South Africa",
    following: "4,1k",
    followers: "2,8m",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author2,
  },
  {
    id: 10,
    firstName: "Elijah",
    lastName: "James",
    address: "Cape Town, South Africa",
    following: "5,1k",
    followers: "3.3m",
    genres: [
      "African",
      "Classics",
      "Contemporary",
      "Feminist Literature",
      "Memories",
      "Psychological Thrillers",
      "True Crime",
    ],
    img: Img.author1,
  },
];

const bookList = [
  {
    id: 1,
    authorName: "Rory Powers",
    name: "Wilder Girls",
    img: Img.book1,
  },
  {
    id: 2,
    authorName: "Louisa May Alcot",
    name: "Little Women",
    img: Img.book2,
  },
  {
    id: 3,
    authorName: "J.K Rowling",
    name: "Harry Potter",
    img: Img.book3,
  },
  {
    id: 4,
    authorName: "J.R.R Tolkien",
    name: "The Lord Of The Rings",
    img: Img.book4,
  },
  {
    id: 5,
    authorName: "Megan Campisi",
    name: "Sin Eater",
    img: Img.book5,
  },
  {
    id: 6,
    authorName: "Khaled Hosseini",
    name: "The Kite Runner",
    img: Img.book6,
  },
  {
    id: 7,
    authorName: "Paulette Jiles",
    name: "News Of The World",
    img: Img.book7,
  },
  {
    id: 8,
    authorName: "J.R.R Tolkien",
    name: "The Lord Of The Rings",
    img: Img.book8,
  },
  {
    id: 9,
    authorName: "J.R.R Tolkien",
    name: "The Lord Of The Rings",
    img: Img.book9,
  },
  {
    id: 10,
    authorName: "Steve Harvey",
    name: "Think and Grow Rich",
    img: Img.book10,
  },
];

export { popularList, authorList, bookList };
